### ISSUE TITLE
Configuration Screen needed

### ISSUE THREAD

**Issue by alanggreen** [FirstLegoLeague/launcher#42]
For the pilot we need to be able to configure two items
1. The tournament name
2. The two sponsor logos on the left bottom and right bottom corners of the screen

## Accessing the Configuration
Add a link to the launcher window (similar to the credits) that will go to a new screen. 
New screen will have a tournament name button/link, left and right sponsor logos buttons/links and a back link.
## Tournament Name
Currently the tournament name is hard coded in the displaySystem display/config.js
This should be moved and written to a json file, possibly in C:\FLL_ScoringSystem\data\config.json
Clicking the button / link should present the user with a method of updating / editing the tournament name. When the input field is shown, it should initially contain the current tournament name.
## Sponsor Logos
Sponsor logos are saved in the directory modules/image-server/images
Clicking the left or right sponsor button/link should open a file selection dialog. User selects an images file and presses OK (or whatever). File is copied to the images directory. and the alias mapping is updated.
Currently the alias mapping is hard coded into modules/image-server/index.ts
The mapping json should be moved into it's own file, or be part of data\config.json
When the image file is copied into the images directory ,the serve:<filename> for sponsor1 or sponsor2 should be updated.
## Update
A way needs to be found to cause the displaySystem to update when the images or the tournament name is updated.

**Comment by kmeesters** [comment]
Hi!

Thanks for the issue, and I do think you raise some good points. However before starting coding I would like to think through the different functions and features that you mention in this issue and see where they best fit in the existing software eco-system. I don't think these are a 'launcher' implemetation. In fact, I would try to keep the 'launcher' as 'dumb' as possible, or in better words: give it a very narrow scope. The whole idea of the eco-system is that we have many micro-services, each with a very specific task. This will make it easier to keep things updated, and being able to replace them. This is in fact the key element of the software architecture (being able to replace components, making it easier for people to pick a single piece). If we integrate too much into one module, we run the risk of going back to the 'monolith' architecture, *and* become depended on a few developers to maintain it.

Specifically for your suggested functions and features I'd break them down into smaller issues and PR in different (or new) modules. Here is a quick (initial) suggestion of what this could be:

- Configuration: 
It might be good to create a new module for this. For two reasons: (1) it will be easier to be re-used for other setups, for example if people are not using the launcher or if someone creates another interface. (2) many other modules will use this as well. For example we can move some of the configuration of scoring to the central config module. For example the tournament name, referees etc. Looking towards the future (where we would also some more public facing modules) having 1 place to configure the tournament (name, date, place, logo etc) would make sense. 
We have already made a first step in a 'wizard' like configuration. This was first in scoring module, (since we didn't had anything else). But now I'd recommend moving this to a separate module. I think it is local on my machine but will push it to my private repro as inspiration.
Needless to say, the configuration module would work via MHub, in fact this is the ideal case for MHub! Offering data and variables to ensure all the modules have the same settings! 

The first step for this would be to create a new module (repro) and draft some initial design requirements for this modules. Also keeping in mind that we should easily be able to expand the configuration settings (variables) in the future (i.e. don't hard-code 'tournament name').

- Name
I think this is split into two modules: there is the actual module that needs to display the name. To change this you don't need to change the files, but rather can push a message through MHub. According to the architecture, modules should not directly alter configuration files in other modules, but rather push messages through MHub or use an API (micro service architecture). Changing files directly (either through a front-end or manually) will break if you deploy servers on different machines (for example in a cloud or distributed setup). 

Having said that, I do agree some of these configuration options should be available 'more directly' to the end user. And I think this will apply to many more configuration options in the future, I'm also thinking about event specific logo's, the data and location of the event. etc. You want to make sure that it is consistently used through the event. So I would suggest to make this a seperate 'global even config' module. Which offers an easy interface to set this variables, and subsequently makes them available through MHub and API (http for images) to other applications. 

- Images  Logo's 
This is basically the same thing as above. I would not integrate this (architectally speaking) in the launcher, but integrate it for example in the imageserver. Or even better: expand the imageserver into a full ' global configuration' module. 

- Concluding remarks:
Looking back at my own text (another Kenny-TM piece of literature :) ). I think it might be good to build a separate module (or rather expand) the image-server, to host both the images and some global variables. The module would then become a sort of place holder for data (blob or other variables) for anything used by other modules. This would be basically a server that offers things via MHub and API (or serve over http). You could even have other modules set this variables if needed. This would include:
- [Season / event Logo's ]  
- [Sponsor Logo's ]  
- [Tournament meta-data (name, date, location, etc) ]  
Then you can also make a nice-front end without trying to integrate everything in the launcher. Making it easier to maintain and distribute development work. Plus it would also work for 'non-launcher' environments. 

For the team and other more 'volatile' information (schedule) we would have to think if it would make more sense to make them into separate modules since they probably require more specialized functionality.  

Added remark at the end regarding 'update': you are right @alanggreen : we need to make sure that a change in this global config, also fires an update on the displaySystem (and other modules). But when using MHub this is already in place.
